spring:  application:    name: GATEWAY-SERVICE  main:    web-application-type: reactive  cloud:    gateway:      routes:      - id : user-service        uri: lb://user-service        predicates:        - Path=/user/**      - id : ticket-booking-service        uri: lb://ticket-booking-service        predicates:        - Path=/booking/**      - id : flight-service        uri: lb://flight-service        predicates:        - Path=/flightService/** server:  port: 4444


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
         defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost